User_Register_Login_Dotnet/User_Register_Login_Dotnet/Models/Dbcontext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;


namespace User_Register_Login_Dotnet.Models
{
    public class Dbcontext
    {
        public SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["mycon"].ConnectionString);

        public bool Add(UserModel um)
        {
            string str = "insert into users values('" + um.Emailid + "','" + um.Password + "','" + um.Name + "')";
            SqlCommand cmd = new SqlCommand(str, con);
            if (con.State == ConnectionState.Closed)
                con.Open();
            int a = cmd.ExecuteNonQuery();
            if(a>=1)
            {
                return true;
            }
            else
            {
                return false; 
            }
        }

                
        public bool Update(UserModel um)
        {
            string str = "update users set emailId='"+um.Emailid + "',password='" + um.Password + "',name='" + um.Name + "'where id='"+um.ID+"'";
            SqlCommand cmd = new SqlCommand(str, con);
            if (con.State == ConnectionState.Closed)
                con.Open();
            int a = cmd.ExecuteNonQuery();
            if (a >= 1)
            {
                return true;
            }
            else
            {
                return false;
            }
        }


        public List<UserModel>GetUser()
        {
            List<UserModel> lst = new List<UserModel>();
            SqlCommand cmd = new SqlCommand("select * from users", con);
            SqlDataAdapter adp = new SqlDataAdapter(cmd);
            DataTable dt = new DataTable();
            adp.Fill(dt);
            foreach (DataRow dr in dt.Rows)
            {
                lst.Add(new UserModel
                {
                    ID = Convert.ToInt32(dr[0]),
                    Emailid = Convert.ToString(dr[1]),
                    Password = Convert.ToString(dr[2]),
                    Name = Convert.ToString(dr[3])

                }
                );
            }

            return lst;
        }



        public List<UserModel> GetbyId(string email)
        {
            List<UserModel> lst = new List<UserModel>();
            SqlCommand cmd = new SqlCommand("select * from users where emailId ='"+email +"'", con);
            SqlDataAdapter adp = new SqlDataAdapter(cmd);
            DataTable dt = new DataTable();
            adp.Fill(dt);
            foreach (DataRow dr in dt.Rows)
            {
                lst.Add(new UserModel
                {
                    ID = Convert.ToInt32(dr[0]),
                    Emailid = Convert.ToString(dr[1]),
                    Password = Convert.ToString(dr[2]),
                    Name = Convert.ToString(dr[3])

                }
                );
            }

            return lst;
        }
    }
}

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace User_Register_Login_Dotnet.Models
{
    public class UserModel
    {
           public int ID { get; set; }
        public int MyProperty { get; set; }



        public string Emailid { get; set; }

        public string Password { get; set; }

        public string Name { get; set; }
    }
}

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace User_Register_Login_Dotnet.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        

    }
}

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Controllers/UserPanelController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using User_Register_Login_Dotnet.Models;



namespace User_Register_Login_Dotnet.Controllers
{
    public class UserPanelController : Controller
    {
        Dbcontext db = new Dbcontext();
        // GET: UserPanel
        public ActionResult Index()
        {
            return View();
        }
    
        [HttpGet]
        public ActionResult Login(string email)
        {
            var row = db.GetUser().FirstOrDefault(model => model.Emailid == email);
            return View(row);

        }


        [HttpPost]
        public ActionResult Login(UserModel um)
        {
            var data = db.GetUser().Where(model => model.Emailid == um.Emailid && model.Password == um.Password).FirstOrDefault();
            if(data != null)
            {
                Session["uid"] = um.Emailid;
                return RedirectToAction("welcome");
            }
            else
            { 
                ViewBag.Showmsg = "Invalid EmailId or Password!!";
                ModelState.Clear();

            }
            return View();

        }


        public ActionResult Welcome()
        {

            var row = db.GetbyId(Session["uid"].ToString());
            
            return View(row);
        }
        

        public ActionResult Create ()
        {
            return View();

        }


        [HttpPost]
        public ActionResult Create(UserModel um)
        {
            db.Add(um);
            return RedirectToAction("Login");

        }
  


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var data = db.GetUser().Where(x => x.ID == id).FirstOrDefault();
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(UserModel um)
        {

            db.Update(um);

            return RedirectToAction("Welcome");
        }

        public ActionResult Logout()
        {

            Session.Clear();

            return RedirectToAction("Login");
        }

    }

}

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/Home/Logout.cshtml
@model IEnumerable<User_Register_Login_Dotnet.Models.UserModel>

@{
    ViewBag.Title = "Logout";
}

<h2>Logout</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Emailid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Emailid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Session["uid"] != null)
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "UserPanel")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/UserPanel/Create.cshtml
@model User_Register_Login_Dotnet.Models.UserModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Emailid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Emailid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Emailid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/UserPanel/Edit.cshtml
@model User_Register_Login_Dotnet.Models.UserModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

       

        <div class="form-group">
            @Html.LabelFor(model => model.Emailid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Emailid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Emailid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/UserPanel/Login.cshtml
@model User_Register_Login_Dotnet.Models.UserModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@Html.Raw(ViewBag.Showmsg)

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserModel</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Emailid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Emailid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Emailid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts { 
    @Scripts.Render("~/bundles/jqueryval")
}

User_Register_Login_Dotnet/User_Register_Login_Dotnet/Views/UserPanel/Welcome.cshtml
@model IEnumerable<User_Register_Login_Dotnet.Models.UserModel>

@{
    ViewBag.Title = "Welcome";
}

<h2>Welcome</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyProperty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Emailid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MyProperty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Emailid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) 
           
           </td>
    </tr>
}

</table>